### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'c:\dev\urandom'

### ISSUE THREAD

**Issue by xehpuk** [glauberportella/password-hash#2]
```
Error: ENOENT: no such file or directory, open 'c:\dev\urandom'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:121:12
    at FSReqCallback.oncomplete (fs.js:157:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'c:\\dev\\urandom'
}
```

**Comment by AniruddhPurohit** [comment]
same error. /dev/urandom is available on ubuntu. but on windows It's not found. I have no idea how to solve it. Please someone help me out

**Comment by andyedward** [comment]
same error. I'm using a windows machine. How to solve this?

**Comment by webup98** [comment]
Same error on windows machine , any updats??

**Comment by disaev1** [comment]
The problem is on the line:
https://github.com/glauberportella/password-hash/blob/cd01fec712d0f5c5bd881e22dd9b0c8d28b336b5/password-hash.js#L75
where `urandom` is used which works with `/dev/urandom`. We can replace `urandom` with `timeRandom` as stated here: https://www.npmjs.com/package/randbytes#get-rand-bytes-from-timestamp
which works for me.

**Comment by callvm** [comment]
> The problem is on the line:
> https://github.com/glauberportella/password-hash/blob/cd01fec712d0f5c5bd881e22dd9b0c8d28b336b5/password-hash.js#L75
> 
> 
> where `urandom` is used which works with `/dev/urandom`. We can replace `urandom` with `timeRandom` as stated here: https://www.npmjs.com/package/randbytes#get-rand-bytes-from-timestamp
> which works for me.

Works for me too. A working Windows version is available here: https://github.com/callvm/password-hash-windows

**Comment by glauberportella** [comment]
No more RandBytes.urandom is used on the repo. But I need someone with Windows to test and gives the feedback.

**Comment by sergiolindau** [comment]
The npm repository was not updated. It contain the 1.0.5 version with old version of get_random_bytes.
