### ISSUE TITLE
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v72-linux-x64-musl.tar.gz 

### ISSUE THREAD

**Issue by leleofg** [glauberportella/password-hash#3]
A versão do bcrypt do projeto precisa do zip: **bcrypt_lib-v3.0.8-node-v72-linux-x64-musl.tar.gz** mas esse arquivo não existe na release 3.0.8. Uma possível solução seria atualizar a versão do bcrypt.

**Comment by glauberportella** [comment]
Você poderia testar novamente esse issue, alterei a dependencia do bcrypt como sugerido em um dos pull requests, agora a dependencia é a bcryptjs.
